language: csharp
solution: OrderMicroservice.sln
dotnet: 7.0

before_install:
  - sudo apt-get update
  - sudo apt-get install -y apt-transport-https

install:
  - wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get update
  - sudo apt-get install -y dotnet-sdk-7.0

script:
  - dotnet --version  # Verify that the correct version is installed
  - dotnet clean
  - dotnet restore
  - dotnet build
