apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: ordermicroservice
  template:
    metadata:
      labels:
        app: ordermicroservice
    spec:
      containers:
        - name: ordermicroservice
          image: gcr.io/ordering-system-404411/ordermicroservice:latest
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: order-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: ordermicroservice
  ports:
  - name: ordermicroservice
    protocol: TCP
    port: 80
    targetPort: 80